<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="6e9092cb68ba" name="TestExample" tests="2" failures="2" timestamp="29 Mar 2018 12:16:51 GMT" time="0.005" errors="0">
  <testcase name="test2" time="0.001" classname="TestExample">
    <failure type="java.lang.AssertionError" message="expected:&lt;1&gt; but was:&lt;0&gt;">
      <![CDATA[java.lang.AssertionError: expected:<1> but was:<0>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at TestExample.test2(TestExample.java:14)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.TestNG.privateMain(TestNG.java:1330)at org.testng.TestNG.main(TestNG.java:1299)]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.004" classname="TestExample">
    <failure type="java.lang.AssertionError" message="expected:&lt;55&gt; but was:&lt;5&gt;">
      <![CDATA[java.lang.AssertionError: expected:<55> but was:<5>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at TestExample.test1(TestExample.java:9)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.TestNG.privateMain(TestNG.java:1330)at org.testng.TestNG.main(TestNG.java:1299)]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- TestExample -->
